<a href="https://colab.research.google.com/github/tnounwy21/ML-23-2-/blob/main/%EA%B8%88%EC%9C%B5_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%88%EB%9F%AC%EC%98%A4%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -U finance-datareader

Collecting finance-datareader
  Downloading finance_datareader-0.9.66-py3-none-any.whl (23 kB)
Requirement already satisfied: pandas>=0.19.2 in /usr/local/lib/python3.10/dist-packages (from finance-datareader) (1.5.3)
Requirement already satisfied: requests>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from finance-datareader) (2.31.0)
Collecting requests-file (from finance-datareader)
  Downloading requests_file-1.5.1-py2.py3-none-any.whl (3.7 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from finance-datareader) (4.9.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from finance-datareader) (4.66.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.19.2->finance-datareader) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.19.2->finance-datareader) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.19.2->finance-datareader) (1.23.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.3.0->finance-datareader) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.3.0->finance-datareader) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.3.0->finance-datareader) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.3.0->finance-datareader) (2023.11.17)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from requests-file->finance-datareader) (1.16.0)
Installing collected packages: requests-file, finance-datareader
Successfully installed finance-datareader-0.9.66 requests-file-1.5.1

In [2]:
import pandas as pd
import FinanceDataReader as fdr

fdr.__version__

'0.9.66'

In [7]:
fdr.StockListing??
# 국내 주식 시장, 한국거래소 상장 종목 전체 가져오기
df_krx = fdr.StockListing("KRX")
df_krx.shape

(2786, 17)

In [8]:
df_kospi = fdr.StockListing("KOSPI")
df_kosdaq = fdr.StockListing("KOSDAQ")

In [13]:
df_kospi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 952 entries, 0 to 951
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Code         952 non-null    object
 1   ISU_CD       952 non-null    object
 2   Name         952 non-null    object
 3   Market       952 non-null    object
 4   Dept         952 non-null    object
 5   Close        952 non-null    object
 6   ChangeCode   952 non-null    object
 7   Changes      952 non-null    int64
 8   ChagesRatio  952 non-null    float64
 9   Open         952 non-null    int64
 10  High         952 non-null    int64
 11  Low          952 non-null    int64
 12  Volume       952 non-null    int64
 13  Amount       952 non-null    int64
 14  Marcap       952 non-null    int64
 15  Stocks       952 non-null    int64
 16  MarketId     952 non-null    object
dtypes: float64(1), int64(8), object(8)
memory usage: 126.6+ KB

In [11]:
df_kosdaq.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1705 entries, 0 to 1704
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Code         1705 non-null   object
 1   ISU_CD       1705 non-null   object
 2   Name         1705 non-null   object
 3   Market       1705 non-null   object
 4   Dept         1705 non-null   object
 5   Close        1705 non-null   object
 6   ChangeCode   1705 non-null   object
 7   Changes      1705 non-null   int64
 8   ChagesRatio  1705 non-null   float64
 9   Open         1705 non-null   int64
 10  High         1705 non-null   int64
 11  Low          1705 non-null   int64
 12  Volume       1705 non-null   int64
 13  Amount       1705 non-null   int64
 14  Marcap       1705 non-null   int64
 15  Stocks       1705 non-null   int64
 16  MarketId     1705 non-null   object
dtypes: float64(1), int64(8), object(8)
memory usage: 226.6+ KB

In [14]:
df_krx.describe()

,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks
count,2786.000000,2786.000000,2786.000000,2786.000000,2786.000000,2.786000e+03,2.786000e+03,2.786000e+03,2.786000e+03
mean,60.622398,0.208270,19571.983489,19946.559943,19242.281048,5.556880e+05,8.062231e+09,8.879866e+11,4.162263e+07
std,1462.384273,3.336819,48481.113975,49445.675424,47921.623374,2.720631e+06,5.170156e+10,9.159936e+12,1.326499e+08
min,-13400.000000,-25.060000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,9.817717e+08,2.000000e+05
25%,-50.000000,-0.790000,2450.000000,2500.000000,2401.250000,1.912750e+04,9.931236e+07,5.533933e+10,1.014977e+07
50%,0.000000,0.000000,6090.000000,6225.000000,6000.000000,8.098750e+04,4.562305e+08,1.117075e+11,1.966842e+07
75%,55.750000,1.020000,15582.500000,15777.500000,15207.500000,2.679105e+05,2.407233e+09,2.808129e+11,4.150249e+07
max,34000.000000,30.000000,702000.000000,705000.000000,700000.000000,8.981218e+07,1.675628e+12,4.375851e+14,5.969783e+09

In [16]:
df_kospi.head()

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,,73300,1,200,0.27,73800,74000,73200,15419815,1134484297093,437585060915000,5969782550,STK
1,000660,KR7000660001,SK하이닉스,KOSPI,,140000,1,3300,2.41,137000,140000,137000,5011719,698129501600,101920331100000,728002365,STK
2,373220,KR7373220003,LG에너지솔루션,KOSPI,,422000,2,-500,-0.12,426500,431000,422000,341008,144990527500,98748000000000,234000000,STK
3,207940,KR7207940008,삼성바이오로직스,KOSPI,,703000,1,5000,0.72,702000,705000,700000,59749,41991591000,50035322000000,71174000,STK
4,005935,KR7005931001,삼성전자우,KOSPI,,59300,2,-600,-1.00,59900,60100,59300,1609498,95959015300,48797181310000,822886700,STK

In [17]:
# csv파일로 저장
df_kospi.to_csv("kospi.csv", index=False) #index값을 빼고 저장
# csv로 저장된 파일을 다시 DateFrame으로 읽어서 확인해보기
pd.read_csv("kospi.csv")

,Code,ISU_CD,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId
0,005930,KR7005930003,삼성전자,KOSPI,NaN,73300,1,200,0.27,73800,74000,73200,15419815,1134484297093,437585060915000,5969782550,STK
1,000660,KR7000660001,SK하이닉스,KOSPI,NaN,140000,1,3300,2.41,137000,140000,137000,5011719,698129501600,101920331100000,728002365,STK
2,373220,KR7373220003,LG에너지솔루션,KOSPI,NaN,422000,2,-500,-0.12,426500,431000,422000,341008,144990527500,98748000000000,234000000,STK
3,207940,KR7207940008,삼성바이오로직스,KOSPI,NaN,703000,1,5000,0.72,702000,705000,700000,59749,41991591000,50035322000000,71174000,STK
4,005935,KR7005931001,삼성전자우,KOSPI,NaN,59300,2,-600,-1.00,59900,60100,59300,1609498,95959015300,48797181310000,822886700,STK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
947,002785,KR7002781003,진흥기업우B,KOSPI,NaN,5020,1,25,0.50,4990,5040,4895,548,2692490,4303234360,857218,STK
948,014915,KR7014911002,성문전자우,KOSPI,NaN,6730,2,-350,-4.94,7540,7540,6700,3076,21072330,4038000000,600000,STK
949,001525,KR7001521004,동양우,KOSPI,NaN,6150,1,30,0.49,6120,6290,6060,1172,7220820,3799045650,617731,STK
950,002787,KR7002782001,진흥기업2우B,KOSPI,NaN,12750,1,160,1.27,12610,12750,12470,105,1394450,3758802000,294808,STK
951,001527,KR7001522002,동양2우B,KOSPI,NaN,11800,3,0,0.00,11750,11800,11530,2301,26781030,3641114200,308569,STK